@startuml
!theme toy

entity "Produto" {
    * id: Long
    --
    nome: String
    descricao: String
    preco: Double
    estoque: int
    ativo: boolean
    --
    adicionarProduto()
    verProduto()
    atualizarProduto()
    excluirProduto()
}

entity "Venda" {
    * id: Long
    --
    data: Date
    total: Double
    --
    adicionarVenda()
    verVenda()
    atualizarVenda()
    excluirVenda()
    relatorioVenda()
}

entity "VendaProduto" {
    * vendaId: Long
    * produtoId: Long
    --
    quantidade: int
}

Produto ||--o{ VendaProduto: contém
Venda ||--o{ VendaProduto: contém

entity "Cache" {
    * id: Long
    --
}
@enduml